
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package act1_analisis_lexico;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int IDENTIFICADOR = 61;
  public static final int AND_LOGICO = 93;
  public static final int MENOR_IGUAL = 91;
  public static final int XOR_ASIGNA = 77;
  public static final int DEFECTO = 29;
  public static final int CONTINUAR = 31;
  public static final int DESP_DER = 101;
  public static final int BORRAR = 45;
  public static final int LLAVE_IZQ = 106;
  public static final int LIT_ENTERO = 62;
  public static final int DIRECTIVA = 5;
  public static final int CON_SIGNO = 16;
  public static final int COR_IZQ = 104;
  public static final int VACIO = 11;
  public static final int VERDADERO = 54;
  public static final int MAYOR = 90;
  public static final int SI = 22;
  public static final int INTERROGACION = 112;
  public static final int DIFERENTE = 88;
  public static final int VIRTUAL = 41;
  public static final int LEER = 58;
  public static final int OPERADOR = 47;
  public static final int MAS_ASIGNA = 70;
  public static final int PAR_DER = 103;
  public static final int ESTE = 43;
  public static final int POR = 82;
  public static final int FALSO = 55;
  public static final int ASIGNA = 69;
  public static final int TAMANIO_DE = 21;
  public static final int XOR_BIT = 98;
  public static final int MODULO_ASIGNA = 74;
  public static final int DOS_PUNTOS = 111;
  public static final int FLECHA = 113;
  public static final int DESP_DER_ASIGNA = 79;
  public static final int LIT_ENTERO_BIN = 65;
  public static final int DESP_IZQ_ASIGNA = 78;
  public static final int BOOLEANO = 10;
  public static final int USANDO = 50;
  public static final int PUNTO_COMA = 109;
  public static final int HACER = 26;
  public static final int PARA = 25;
  public static final int DIRECTIVA_DEFINIR = 4;
  public static final int RESOLUCION = 114;
  public static final int INCREMENTO = 85;
  public static final int FIN_LINEA = 59;
  public static final int COMA = 108;
  public static final int ESTRUCTURA = 35;
  public static final int ENTERO = 6;
  public static final int MODULO = 84;
  public static final int IGUAL = 87;
  public static final int DOBLE = 8;
  public static final int CLASE = 34;
  public static final int PRIVADO = 39;
  public static final int UNION = 36;
  public static final int DESP_IZQ = 100;
  public static final int OR_ASIGNA = 76;
  public static final int AMIGO = 42;
  public static final int INCLUIR = 2;
  public static final int PLANTILLA = 46;
  public static final int LIT_CADENA = 67;
  public static final int IMPRIMIR = 57;
  public static final int TIPO_DEF = 20;
  public static final int DECREMENTO = 86;
  public static final int IR_A = 33;
  public static final int ENTRE_ASIGNA = 73;
  public static final int OR_LOGICO = 94;
  public static final int MENOS = 81;
  public static final int MENOR = 89;
  public static final int MAS = 80;
  public static final int NULO = 56;
  public static final int LIT_CARACTER = 68;
  public static final int PAR_IZQ = 102;
  public static final int EOF = 0;
  public static final int MIENTRAS = 24;
  public static final int PUNTO = 110;
  public static final int LLAVE_DER = 107;
  public static final int COR_DER = 105;
  public static final int NOT_BIT = 99;
  public static final int CONSTANTE = 18;
  public static final int CARACTER = 9;
  public static final int INTENTAR = 51;
  public static final int EN_LINEA = 48;
  public static final int ENTRE = 83;
  public static final int SEGUN = 27;
  public static final int PRINCIPAL = 60;
  public static final int ROMPER = 30;
  public static final int error = 1;
  public static final int LIT_ENTERO_HEX = 63;
  public static final int ENUMERACION = 37;
  public static final int LIT_FLOTANTE = 66;
  public static final int LANZAR = 53;
  public static final int SINO = 23;
  public static final int RUTA_INCLUSION = 3;
  public static final int CORTO = 14;
  public static final int NOT_LOGICO = 95;
  public static final int CASO = 28;
  public static final int PROTEGIDO = 40;
  public static final int FLOTANTE = 7;
  public static final int LARGO = 13;
  public static final int RETORNAR = 32;
  public static final int ESTATICO = 19;
  public static final int CADENA = 12;
  public static final int LIT_ENTERO_OCT = 64;
  public static final int SIN_SIGNO = 15;
  public static final int POR_ASIGNA = 72;
  public static final int PUBLICO = 38;
  public static final int AND_BIT = 96;
  public static final int AND_ASIGNA = 75;
  public static final int MENOS_ASIGNA = 71;
  public static final int OR_BIT = 97;
  public static final int MAYOR_IGUAL = 92;
  public static final int ESPACIO_NOMBRES = 49;
  public static final int NUEVO = 44;
  public static final int AUTO = 17;
  public static final int CAPTURAR = 52;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "INCLUIR",
  "RUTA_INCLUSION",
  "DIRECTIVA_DEFINIR",
  "DIRECTIVA",
  "ENTERO",
  "FLOTANTE",
  "DOBLE",
  "CARACTER",
  "BOOLEANO",
  "VACIO",
  "CADENA",
  "LARGO",
  "CORTO",
  "SIN_SIGNO",
  "CON_SIGNO",
  "AUTO",
  "CONSTANTE",
  "ESTATICO",
  "TIPO_DEF",
  "TAMANIO_DE",
  "SI",
  "SINO",
  "MIENTRAS",
  "PARA",
  "HACER",
  "SEGUN",
  "CASO",
  "DEFECTO",
  "ROMPER",
  "CONTINUAR",
  "RETORNAR",
  "IR_A",
  "CLASE",
  "ESTRUCTURA",
  "UNION",
  "ENUMERACION",
  "PUBLICO",
  "PRIVADO",
  "PROTEGIDO",
  "VIRTUAL",
  "AMIGO",
  "ESTE",
  "NUEVO",
  "BORRAR",
  "PLANTILLA",
  "OPERADOR",
  "EN_LINEA",
  "ESPACIO_NOMBRES",
  "USANDO",
  "INTENTAR",
  "CAPTURAR",
  "LANZAR",
  "VERDADERO",
  "FALSO",
  "NULO",
  "IMPRIMIR",
  "LEER",
  "FIN_LINEA",
  "PRINCIPAL",
  "IDENTIFICADOR",
  "LIT_ENTERO",
  "LIT_ENTERO_HEX",
  "LIT_ENTERO_OCT",
  "LIT_ENTERO_BIN",
  "LIT_FLOTANTE",
  "LIT_CADENA",
  "LIT_CARACTER",
  "ASIGNA",
  "MAS_ASIGNA",
  "MENOS_ASIGNA",
  "POR_ASIGNA",
  "ENTRE_ASIGNA",
  "MODULO_ASIGNA",
  "AND_ASIGNA",
  "OR_ASIGNA",
  "XOR_ASIGNA",
  "DESP_IZQ_ASIGNA",
  "DESP_DER_ASIGNA",
  "MAS",
  "MENOS",
  "POR",
  "ENTRE",
  "MODULO",
  "INCREMENTO",
  "DECREMENTO",
  "IGUAL",
  "DIFERENTE",
  "MENOR",
  "MAYOR",
  "MENOR_IGUAL",
  "MAYOR_IGUAL",
  "AND_LOGICO",
  "OR_LOGICO",
  "NOT_LOGICO",
  "AND_BIT",
  "OR_BIT",
  "XOR_BIT",
  "NOT_BIT",
  "DESP_IZQ",
  "DESP_DER",
  "PAR_IZQ",
  "PAR_DER",
  "COR_IZQ",
  "COR_DER",
  "LLAVE_IZQ",
  "LLAVE_DER",
  "COMA",
  "PUNTO_COMA",
  "PUNTO",
  "DOS_PUNTOS",
  "INTERROGACION",
  "FLECHA",
  "RESOLUCION"
  };
}

